import type { SentinelReport } from "../../types/index.js";

export function formatMarkdown(report: SentinelReport): string {
  const lines: string[] = [];

  lines.push("# Sentinel — AI Fingerprint Report");
  lines.push("");
  lines.push(`**Repository:** \`${report.repoPath}\``);
  if (report.commitRange) {
    lines.push(`**Commit Range:** \`${report.commitRange}\``);
  }
  lines.push(`**Generated:** ${report.generatedAt}`);
  lines.push(`**Files Analyzed:** ${report.totalFiles}`);
  lines.push(`**Lines Changed:** +${report.totalAddedLines} / -${report.totalRemovedLines}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  if (report.summary.dominantModel) {
    lines.push(
      `- **Dominant Model:** ${report.summary.dominantModel.displayName} (${(report.summary.dominantModel.confidence * 100).toFixed(1)}% confidence)`,
    );
  } else {
    lines.push("- **Dominant Model:** No strong signal detected");
  }
  lines.push(`- **Risk Level:** ${report.summary.riskScore.toUpperCase()}`);
  lines.push("");

  // Model attribution table
  if (report.summary.modelBreakdown.length > 0) {
    lines.push("## Model Attribution");
    lines.push("");
    lines.push("| Model | Confidence | Patterns Matched |");
    lines.push("|-------|-----------|-----------------|");
    for (const score of report.summary.modelBreakdown) {
      lines.push(
        `| ${score.displayName} | ${(score.confidence * 100).toFixed(1)}% | ${score.matches.length} |`,
      );
    }
    lines.push("");
  }

  // File analysis table
  lines.push("## File Analysis");
  lines.push("");
  lines.push("| File | +/- | Top Model | Confidence |");
  lines.push("|------|-----|-----------|-----------|");
  for (const analysis of report.files) {
    const top = analysis.topModel;
    lines.push(
      `| \`${analysis.file.newPath}\` | +${analysis.file.addedLines}/-${analysis.file.removedLines} | ${top?.displayName ?? "—"} | ${top ? `${(top.confidence * 100).toFixed(0)}%` : "—"} |`,
    );
  }
  lines.push("");

  // Unprompted changes
  if (report.summary.unpromptedChanges.length > 0) {
    lines.push("## Unprompted Changes");
    lines.push("");
    lines.push("| File | Risk | Description |");
    lines.push("|------|------|-------------|");
    for (const change of report.summary.unpromptedChanges) {
      const emoji = change.risk === "high" ? "🔴" : change.risk === "medium" ? "🟡" : "🔵";
      lines.push(`| \`${change.file}\` | ${emoji} ${change.risk} | ${change.description} |`);
    }
    lines.push("");
  }

  // Recommendations
  if (report.summary.recommendations.length > 0) {
    lines.push("## Recommended Next Actions");
    lines.push("");
    lines.push("| Priority | Action | Affected Files | Rationale |");
    lines.push("|----------|--------|----------------|-----------|");
    for (const rec of report.summary.recommendations) {
      const files = rec.affectedFiles.length > 0 ? rec.affectedFiles.map((file) => `\`${file}\``).join("<br>") : "—";
      lines.push(`| ${rec.priority} | **${rec.title}**<br>${rec.description} | ${files} | ${rec.rationale} |`);
    }
    lines.push("");
  }

  // Evidence
  if (report.summary.evidenceTrail.length > 0) {
    lines.push("## Evidence Trail");
    lines.push("");
    for (const ev of report.summary.evidenceTrail.slice(0, 30)) {
      lines.push(`- **\`${ev.file}\`**: ${ev.snippet}`);
    }
    if (report.summary.evidenceTrail.length > 30) {
      lines.push(`- *... and ${report.summary.evidenceTrail.length - 30} more*`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [Sentinel](https://github.com/mikelaurenzo7-collab/Neural-Scrub)*");

  return lines.join("\n");
}
